apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angular-app-azure 
spec: 
  selector: 
    matchLabels: 
      app: angular-app-azure 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: angular-app-azure 
    spec: 
      containers: 
      - name: angular-app-azure 
        image: dockerkumart/angular-app:#{Build.BuildId}#
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angular-app-azure
spec: 
  selector: 
    app: angular-app-azure 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 